### ISSUE TITLE
How does `virtual-raf` compare to `main-loop`?

### ISSUE THREAD

**Issue by serapath** [yoshuawuyts/virtual-raf#1]
Hey, I stumbled upon `virtual-raf`.
I was using a module called `main-loop` (https://github.com/Raynos/main-loop) for some time, but I like `virtual-raf` because it's easier for me to follow the code :-) Otherwise, there are some differences in the exposed API. Are there special thoughts behind the slightly different design?

**Comment by yoshuawuyts** [comment]
Hey yeah, so I screwed up the design of [wayfarer](https://github.com/yoshuawuyts/wayfarer) which requires a custom `renderer` function on each subsequent call because it doesn't return stuff. Which is bad. Very bad.

Once I fix `wayfarer` I think I'll just recommend people to use `main-loop` or mirror the code there or something. The idempotent stuff in `virtual-raf` should be treated with care, as it's a bit hacky.

Does this answer your question? Closing for now, lmk if you want a more detailed explanation.

**Comment by serapath** [comment]
i was kind of hoping that `main-loop` and `virtual-raf` are equivalent. I prefer the code in `virtual-raf` and while searching `npm` initially, the `virtual-raf` was way more intuitive when it comes to thinking of what to search for. I don't think that I understand what you are saying, but if `main-loop` is what you would recommend that's fine, i just find it harder to read and it's also 20 lines longer

**Comment by yoshuawuyts** [comment]
yeah, I prefer my code too. I might keep it around then; they're basically the same thing, but `virtual-raf` can do a little bit more.
